// Helper function to write to extension logs in storage
async function logToStorage(type, message, details = null) {
  const timestamp = new Date().toISOString();
  const logEntry = { timestamp, type, message, details };
  
  const data = await chrome.storage.local.get(['logs']);
  let logs = data.logs || [];
  logs.unshift(logEntry);
  if (logs.length > 50) {
    logs = logs.slice(0, 50);
  }
  await chrome.storage.local.set({ logs });
  
  // Broadcast log update to the popup if it is open
  chrome.runtime.sendMessage({ type: 'LOGS_UPDATED', logs }).catch(() => {
    // Ignore error if popup is not open
  });
}



// Primary sync logic
async function runSync() {
  await logToStorage('info', 'Starting cookie synchronization...');
  
  try {
    // 1. Get configurations from storage
    const { config } = await chrome.storage.local.get(['config']);
    const customSubdomain = config?.subdomain?.trim();
    const apiUrl = config?.apiUrl?.trim() || 'https://linatai008-n8n.hf.space/form/79319c3e-265d-4a25-a8c0-6e737bdfa53f';
    
    if (!customSubdomain) {
      await logToStorage('error', 'Sync failed: Feishu subdomain is not configured. Please enter your subdomain in settings.');
      await chrome.storage.local.set({
        lastSyncSuccess: false
      });
      return;
    }
    
    let subdomainsToSync = [customSubdomain];
    await logToStorage('info', `Using configured subdomain: ${customSubdomain}`);
    
    // 3. Sync cookies for each subdomain
    let successCount = 0;
    for (const user of subdomainsToSync) {
      try {
        const targetUrl = `https://${user}.feishu.cn/minutes/me`;
        await logToStorage('info', `Retrieving cookies for: ${targetUrl}`);
        
        const targetCookies = await chrome.cookies.getAll({ url: targetUrl });
        
        if (targetCookies.length === 0) {
          await logToStorage('warning', `No cookies retrieved for user/subdomain: ${user}. Please visit the webpage to log in.`);
          continue;
        }
        
        // Format cookies as "key1=val1; key2=val2"
        const cookieHeaderStr = targetCookies.map(c => `${c.name}=${c.value}`).join('; ');
        
        await logToStorage('info', `Uploading cookies for user "${user}" to Webhook`);
        
        // n8n Form trigger v2 expects inputs to be submitted with key names
        // matching the field IDs (field-0, field-1, etc.) generated by the frontend.
        // It then maps these back to the configured labels ('user' and 'cookies') on the server.
        const formData = new FormData();
        formData.append('field-0', user);
        formData.append('field-1', cookieHeaderStr);
        
        const response = await fetch(apiUrl, {
          method: 'POST',
          body: formData
        });
        
        const respText = await response.text();
        
        if (response.ok) {
          successCount++;
          await logToStorage('success', `Successfully synced cookies for user "${user}"`, {
            status: response.status,
            response: respText.substring(0, 200)
          });
        } else {
          await logToStorage('error', `Failed to upload cookies for user "${user}"`, {
            status: response.status,
            statusText: response.statusText,
            response: respText.substring(0, 500)
          });
        }
      } catch (err) {
        await logToStorage('error', `Failed sync loop for user "${user}" due to exception`, {
          message: err.message,
          stack: err.stack
        });
      }
    }
    
    // Record execution state
    const syncTime = new Date().toISOString();
    await chrome.storage.local.set({
      lastSyncTime: syncTime,
      lastSyncSuccess: successCount > 0
    });
    
  } catch (error) {
    await logToStorage('error', 'Sync failed with an uncaught exception', {
      message: error.message,
      stack: error.stack
    });
    await chrome.storage.local.set({
      lastSyncSuccess: false
    });
  }
}

// Startup & Installation Listener
chrome.runtime.onInstalled.addListener(async (details) => {
  await logToStorage('info', `Extension initialized. Action: ${details.reason}`);
  
  // Clear any legacy alarms and nextSyncTime state
  if (chrome.alarms) {
    await chrome.alarms.clearAll();
  }
  await chrome.storage.local.remove('nextSyncTime');
  
  const { config } = await chrome.storage.local.get(['config']);
  if (!config) {
    await chrome.storage.local.set({
      config: {
        subdomain: '',
        apiUrl: 'https://linatai008-n8n.hf.space/form/79319c3e-265d-4a25-a8c0-6e737bdfa53f'
      }
    });
  }
});

chrome.runtime.onStartup.addListener(async () => {
  await logToStorage('info', 'Extension background service worker started.');
  if (chrome.alarms) {
    await chrome.alarms.clearAll();
  }
  await chrome.storage.local.remove('nextSyncTime');
});

// Listener for force sync from popup
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.type === 'FORCE_SYNC') {
    runSync().then(() => {
      sendResponse({ success: true });
    }).catch(err => {
      sendResponse({ success: false, error: err.message });
    });
    return true; // asynchronous response
  }
});
